import ThemeRegistry from '@/components/ThemeRegistry';
import { Paper } from '@mui/material';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <ThemeRegistry>
        <body>
          <Paper>
            <h2>test</h2>
            {children}
          </Paper>
        </body>
      </ThemeRegistry>
    </html>
  );
}
