import { Box, Paper } from '@mui/material';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function TestLayout({ children }: { children: React.ReactNode }) {
  return (
    <Box>
      <Paper>
        <h2>Cringe layout</h2>
      </Paper>
      {children}
    </Box>
  );
}
